#!/bin/bash

: ${AVRCHIP:=m328p}
: ${AVRPROGRAMMER:=dragon_isp}
: ${AVRBAUD:=4}

case $1 in
	burn)
		if [ -z "$2" ]; then
			echo "Please specify a HEX file!"
			exit
		fi
		avrdude -c $AVRPROGRAMMER -p $AVRCHIP -B $AVRBAUD -U "flash:w:$2"
		;;
	burn-fuses)
		if [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
			: ${EFUSE:=0x05}
			: ${HFUSE:=0xDA}
			: ${LFUSE:=0xD6}
			echo "Using default flag values of E:$EFUSE H:$HFUSE L:$LFUSE"
		else
			: ${EFUSE:="$2"}
			: ${HFUSE:="$3"}
			: ${LFUSE:="$4"}
		fi
		avrdude -c $AVRPROGRAMMER -p $AVRCHIP -B $AVRBAUD -U lfuse:w:"$LFUSE":m hfuse:w:"$HFUSE":m -U efuse:w:"$EFUSE":m
		;;
	erase)
		avrdude -c $AVRPROGRAMMER -p $AVRCHIP -B $AVRBAUD -e
		;;
	enable-debug)
		avrdude -c $AVRPROGRAMMER -p $AVRCHIP -B $AVRBAUD -U hfuse:w:0x9A:m
		;;
	disable-debug)
		avrdude -c $AVRPROGRAMMER -p $AVRCHIP -B $AVRBAUD -U hfuse:w:0xDA:m
		;;
	debug)
		avarice -gw :4040
		;;
	gdb)
		if [ -z "$2" ]; then
			echo "Please specify an ELF file!"
			exit
		fi
		avr-gdb "$2" --eval-command="target remote localhost:4040"
		;;
	*)
		echo "Usage: $0 COMMAND"
		echo "Valid commands are:"
		echo "  burn \$hexfile                       Burns a HEX file to the target"
		echo "  burn-fuses [\$efuse \$hfuse \$lfuse]   Burns fuses to the target (explicit flags are optional)"
		echo "  erase                               Erases the target"
		echo "  enable-debug                        Enables DebugWIRE on the target"
		echo "  disable-debug                       Disables DebugWIRE on the target"
		echo "  debug                               Launches AVaRICE to debug a target"
		echo "  gdb \$elffile                        Launches GDB with an ELF file and connects to AVaRICE"
		echo
		echo "The current avrdude configurables are:"
		echo "AVRCHIP: $AVRCHIP"
		echo "AVRPROGRAMMER: $AVRPROGRAMMER"
		echo "AVRBAUD: $AVRBAUD"
		echo "These are environment variables which you may override."
		;;
esac

